DROP TABLE IF EXISTS pogrzeby;
DROP TABLE IF EXISTS malzenstwa;
DROP TABLE IF EXISTS bierzmowania;
DROP TABLE IF EXISTS komunie;
DROP TABLE IF EXISTS chrzty;
DROP TABLE IF EXISTS kaplani;
DROP TABLE IF EXISTS parafianie;