DROP SEQUENCE IF EXISTS ID_SEQ CASCADE;


DROP VIEW IF EXISTS pomocnicy CASCADE;
DROP VIEW IF EXISTS ministranci CASCADE;
DROP VIEW IF EXISTS lektorzy CASCADE;
DROP VIEW IF EXISTS szafarze CASCADE;
DROP VIEW IF EXISTS ofiary CASCADE;
DROP VIEW IF EXISTS aktywnosci_kaplanow CASCADE;
DROP VIEW IF EXISTS zmarli CASCADE;
DROP VIEW IF EXISTS chrzty_szczegoly CASCADE;
DROP VIEW IF EXISTS bierzmowania_szczegoly CASCADE;

DROP TABLE IF EXISTS intencje_mszalne CASCADE;
DROP TABLE IF EXISTS wizyty_duszpasterskie CASCADE;
DROP TABLE IF EXISTS pogrzeby CASCADE;
DROP TABLE IF EXISTS sluby CASCADE;
DROP TABLE IF EXISTS bierzmowania CASCADE;
DROP TABLE IF EXISTS pierwsze_komunie CASCADE;
DROP TABLE IF EXISTS chrzty CASCADE;
DROP TABLE IF EXISTS pomocnicy CASCADE;
DROP TABLE IF EXISTS kaplani CASCADE;
DROP TABLE IF EXISTS pomocnicy_funkcje CASCADE;
DROP TABLE IF EXISTS parafianie CASCADE;

DROP FUNCTION IF EXISTS check_pesel();
DROP FUNCTION IF EXISTS handle_chrzest();
DROP FUNCTION IF EXISTS handle_pogrzeb();
DROP FUNCTION IF EXISTS handle_slub();
DROP FUNCTION IF EXISTS handle_bierzmowanie();
DROP FUNCTION IF EXISTS count_pesel_checksum(pesel char(11));