package db.utils;

/**
 * @author Katarzyna Janocha, Michał Piekarz
 */
public enum Tables {
    KAPLANI, PARAFIANIE, POMOCNICY_FUNKCJE, CHRZTY, PIERWSZE_KOMUNIE, BIERZMOWANIA, SLUBY, POGRZEBY, WIZYTY_DUSZPASTERSKIE, INTENCJE_MSZALNE
}
